// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7C8yFN5rmuc42VSTUkArkgBy8_t4NoAw',
    appId: '1:595685635413:web:453b65c0ee1d5142412bdc',
    messagingSenderId: '595685635413',
    projectId: 'lesson72-49741',
    authDomain: 'lesson72-49741.firebaseapp.com',
    storageBucket: 'lesson72-49741.appspot.com',
    measurementId: 'G-TMHVCYWH4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbNo1nURlFLc71CcniAXlEQsZX5I8c3VA',
    appId: '1:595685635413:android:6eee20ee80e87db9412bdc',
    messagingSenderId: '595685635413',
    projectId: 'lesson72-49741',
    storageBucket: 'lesson72-49741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4OQJpMgtmKWIK3Y_J5zPvQZuJ_naP9k8',
    appId: '1:595685635413:ios:7da3d01861024f2b412bdc',
    messagingSenderId: '595685635413',
    projectId: 'lesson72-49741',
    storageBucket: 'lesson72-49741.appspot.com',
    iosBundleId: 'com.example.flutterLesson76',
  );
}
